[package]
name = "bevy_xpbd_3d"
version = "0.1.0"
edition = "2021"

[features]
default = [ "3d" ]
3d = []
debug-render-aabbs = []

[lib]
name = "bevy_xpbd_3d"
path = "../../src/lib.rs"
required-features = [ "3d" ]

[dependencies]
bevy = { version = "0.9.1", default-features = false }
bevy_prototype_debug_lines = { version = "0.9", features = [ "3d" ] }
parry3d = { version = "0.13.1" }
nalgebra = { version = "0.32.1", features = [ "convert-glam022" ] }
console_error_panic_hook = "0.1"
web-sys = "0.3.59"

[dev-dependencies]
examples_common_3d = { path = "../examples_common_3d" }
