[package]
name = "bevy_xpbd_2d"
version = "0.1.0"
edition = "2021"

[features]
default = [ "2d" ]
2d = []
debug-render-aabbs = []

[lib]
name = "bevy_xpbd_2d"
path = "../../src/lib.rs"
required-features = [ "2d" ]

[dependencies]
bevy = { version = "0.9.1", default-features = false }
bevy_prototype_debug_lines = "0.9"
parry2d = { version = "0.13.1", features = [ "simd-stable" ] }
nalgebra = { version = "0.32.1", features = [ "convert-glam022" ] }
console_error_panic_hook = "0.1.7"
web-sys = "0.3.59"

[dev-dependencies]
examples_common_2d = { path = "../examples_common_2d" }
